//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by LoadLibraryExplorer.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_LOADLIBRARYEXPLORER_DIALOG  102
#define IDS_TRACELOG_UNKNOWN_ERROR      102
#define IDS_UNKNOWN_ERROR               103
#define IDS_TRACELOG_FILTER             104
#define IDS_TRACELOG_DELETED_ENTRIES    105
#define IDS_TRACELOG_FILE_SAVE          106
#define IDS_TRACELOG_FILE_SAVE_AS       107
#define IDS_TRACELOG_FILE_OPEN_FAILED   108
#define IDS_CREATED_DIRECTORY           109
#define IDS_DIRECTORY_EXISTS            110
#define IDS_DIRECTORY_ERROR             111
#define IDS_PROGRAM_ROOT                112
#define IDS_REGISTRY_SYSTEM32           113
#define IDS_REGISTRY_WINDOWS            114
#define IDS_REGISTRY_WORKING            115
#define IDS_CD_FAILED                   116
#define IDS_CD_WORKED                   117
#define IDS_REGISTRY_APP_PATH           118
#define IDS_REGISTRY_SAFEDLLSEARCHMODE  119
#define IDS_REGISTRY_SAFEDLLSEARCHMODE_HKLM 119
#define IDS_CANT_STORE_SAFEDLLSEARCHMODE 120
#define IDS_APP_PATH                    121
#define IDS_GETDLLNAME_FAILED           122
#define IDS_GETPROCADDRESS_FAILED       123
#define IDS_LOAD_FAILED                 124
#define IDS_GETDLLNAME_WORKD            125
#define IDS_SHELLEXECUTE_NOT_IMPLEMENTED 126
#define IDS_GETDLLNAME_WORKED           127
#define IDR_MAINFRAME                   128
#define IDS_DELETED_DLL                 128
#define IDS_DELETE_FAILED               129
#define IDI_JMN                         129
#define IDS_STARS                       130
#define IDR_DLL                         130
#define IDS_NO_SOURCE_DLL               131
#define IDS_DLL_SAME                    132
#define IDS_QUERY_TARGET_FAILED         133
#define IDS_SET_TARGET_FAILED           134
#define IDS_COPY_TARGET_FAILED          135
#define IDS_REGISTRY_EXECUTABLE         136
#define IDS_REGISTRY_ALTERNATE          137
#define IDS_DELETE_NOT_NEEDED           138
#define IDS_REGISTRY_FORCE_SELECTION    139
#define IDS_REGISTRY_FORCE              140
#define IDS_PATH_SET                    141
#define IDS_REGISTRY_USE_SAFEDLLSEARCHMODE 142
#define IDS_REGISTRY_USE_SAFEDLLSEARCHMODE_SETTING 143
#define IDS_LINE                        144
#define IDS_SET_SAFEDLLSEARCHMODE       145
#define IDS_REGISTRY_LOAD_WITH_ALTERED_SEARCH_PATH 146
#define IDS_REGISTRY_LOADTYPE           147
#define IDS_ENUM_FAILED                 148
#define IDS_MODULE_LIST                 149
#define IDS_COPY_TARGET_WORKED          150
#define IDS_BAD_MODULE_HANDLE           151
#define IDS_KNOWN_DLLS                  152
#define IDS_KNOWN_DLL                   153
#define IDS_KNOWN_DLL_FAILURE           154
#define IDS_APPPATH_FAILED              155
#define IDS_APPPATH_SET                 156
#define IDS_APPPATH_NOT_DELETED         157
#define IDS_APPPATH_DELETED             158
#define IDS_APPPATH_PATH_FAILED         159
#define IDS_APPPATH_PATH_SET            160
#define IDS_RELAUNCH_FAILED             161
#define IDS_INITIAL_APP_PATH            162
#define IDS_NO_INITIAL_APP_PATH         163
#define IDS_RELAUNCH_REQUIRED           164
#define IDS_REGISTRY_RELAUNCH           165
#define IDS_REGISTRY_WINDOWPLACEMENT    166
#define IDS_SOURCE_ERROR                167
#define IDS_TARGET_ERROR                168
#define IDS_SOURCE_SAME                 169
#define IDS_COPY_ERROR                  170
#define IDS_COPY_OK                     171
#define IDS_ALREADY_DELETED             172
#define IDS_DELETE_FAILED2              173
#define IDS_DELETE_OK                   174
#define IDS_REGISTRY_DLL_SELECTION      175
#define IDS_REGISTRY_KNOWN_DLL          176
#define IDS_SYSTEM32_PRESENT            177
#define IDS_GET_ATTRIBUTES_FAILED       178
#define IDS_SET_ATTRIBUTES_FAILED       179
#define IDS_REGISTRY_SYSTEM             180
#define IDS_SETDLLDIRECTORY             181
#define IDS_SETDLLDIRECTORY_NULL        182
#define IDS_SETDLLDIRECTORY_FAILED      183
#define IDS_NO_LOCAL_FOUND              184
#define IDS_LOCAL_IS_FILE               185
#define IDS_LOCAL_FILENAME_DELETE_FAILED 186
#define IDS_LOCAL_FILENAME_DELETE_SUCCEEDED 187
#define IDS_LOCAL_DIRECTORY_EMPTY       188
#define IDS_LOCAL_DIRECTORY_DELETE_FAILED 189
#define IDS_LOCAL_DIRECTORY_DELETED     190
#define IDS_LOCAL_IS_DIRECTORY          191
#define IDS_LOCAL_FILE_DELETE_FAILED    192
#define IDS_LOCAL_FILE_DELETED          193
#define IDS_CREATE_REDIRECT_FILE_FAILED 194
#define IDS_CREATE_REDIRECT_FILE        195
#define IDS_REDIRECTION_DIRECTORY_FAILED 196
#define IDS_REDIRECTION_DIRECTORY_EXISTS 197
#define IDS_REDIRECTION_DIRECTORY_WRONG 198
#define IDS_INSTALL_REDIRECTED_DLL_FAILED 199
#define IDS_REGISTRY_REDIRECTION        200
#define IDS_DIRECTORY_IN_LOCAL          201
#define IDS_PROCESS_TERMINATED_OK       202
#define IDS_PROCESS_TERMINATED_BADLY    203
#define IDS_LAUNCH_FAILED               204
#define IDS_BAD_SIGNATURE               205
#define IDS_PROCESS_LOADED              206
#define IDS_PROCESS_ERROR               207
#define IDS_REGISTRY_TEST_SAFE_DLL_SEARCH_MODE 208
#define IDS_ERROR_GETTING_EXE_DATE      209
#define IDS_NO_DLL_FOUND                210
#define IDS_DLL_CURRENT                 211
#define IDS_DLL_RESOURCE_FAILURE        212
#define IDS_DLL_RESOURCE_ZERO_SIZE      213
#define IDS_DLL_RESOURCE_LOAD_FAILED    214
#define IDS_DLL_LOCK_FAILED             215
#define IDS_DLL_CREATE_FAILED           216
#define IDS_ERROR_WRITING_DLL           217
#define IDS_DLL_EXTRACTED               218
#define IDC_LOG                         1000
#define IDC_SYSTEM32                    1001
#define IDC_WINDOWS                     1002
#define IDC_WORKING                     1003
#define IDC_APP_PATH                    1004
#define IDC_APPDIR                      1004
#define IDC_SAFEDLLSEARCHMODE           1005
#define IDC_PATH                        1007
#define IDC_LIBRRARY                    1008
#define IDC_LOAD                        1009
#define IDC_LOADLIBRARY                 1010
#define IDC_USE_LOADLIBRARY             1011
#define IDC_USE_LOADLIBRARYEX           1012
#define IDC_USE_SHELLEXECUTE            1013
#define IDC_LOAD_WITH_ALTERED_SEARCH_PATH 1014
#define IDC_EXECUTABLE                  1015
#define IDC_SYSTEM                      1016
#define IDC_ALTERNATE                   1017
#define IDC_FORCE_SYSTEM32              1018
#define IDC_LOCAL_REDIRECT              1019
#define IDC_FORCE_WINDOWS               1020
#define IDC_FORCE_SYSTEM                1021
#define IDC_FORCE_WORKING               1022
#define IDC_FORCE_APP_PATH              1023
#define IDC_FORCE_EXECUTABLE            1024
#define IDC_FORCE_ALTERNATE             1025
#define IDC_FORCE                       1026
#define IDC_DEFAULT_SAFE_DLL_SEARCH_MODE 1029
#define IDC_FORCE_SAFEDLLSEARCHMODE     1030
#define IDC_DESIRED_SAFEDLLSEARCHMODE   1030
#define IDC_ENUM                        1032
#define IDC_ALPHABETICAL                1033
#define IDC_KNOWN_DLLS                  1034
#define IDC_RELAUNCH                    1035
#define IDC_MESSAGE                     1036
#define IDC_STATE_SYSTEM32              1037
#define IDC_STATE_WINDOWS               1038
#define IDC_STATE_SYSTEM                1039
#define IDC_STATE_WORKING               1040
#define IDC_STATE_APP_PATH              1041
#define IDC_STATE_EXECUTABLE            1042
#define IDC_STATE_ALTERNATE             1043
#define IDC_USE_THE_DLL                 1044
#define IDC_KNOWN_DLL                   1045
#define IDC_STATE_LOCAL                 1046
#define IDC_DLL_DIRECTORY               1047
#define IDC_USE_SELECTED_SAFEDLLSEARCHMODE 1048
#define IDC_USE_DEFAULT_SEARCH_MODE     1049
#define IDC_REDIRECT_NONE               1050
#define IDC_REDIRECT_EXECUTABLE         1051
#define IDC_REDIRECT_LOCAL              1052
#define IDC_REDIRECT_CAPTION            1053
#define IDC_DLL_LOCATIONS_CAPTION       1054
#define IDC_MINFRAME                    1055
#define IDC_TEST_SAFE                   1057
#define IDC_DIALOG_SELECTION_CAPTION    1058
#define IDC_LOAD_METHOD_CAPTION         1059

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1060
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
